[env]

  [env._]

    [env._.python]

      [env._.python.venv]
        create = true
        path   = ".venv"

[tools]
  golang = "1.25.6"
  nodejs = "22.15.1"
  pnpm   = "10.24.0"
  python = "3.12.10"
  uv     = "latest"
